language: node_js
node_js:
- 10.14.0
cache:
  directories:
  - node_modules
before_install:
- npm install hexo-cli -g
install:
- npm install
script:
- hexo clean
- hexo generate
- hexo d
after_script:
  - cd ./public
  - git init
  - git config user.name "lanpangzhi"
  - git config user.email "875727617@qq.com"
  - git add .
  - git commit -m "TravisCI 自动部署"
  # Github Pages
  - git push --force --quiet "https://${CI_TOKEN}@${GH_REF}" master:master 
  # Coding Pages
  # - git push --force --quiet "https://bule:${CO_TOKEN}@${CO_REF}" master:master

branches:
  only:
  - indigo

env:
 global:
   # Github Pages
   - GH_REF: github.com/lanpangzhi/lanpangzhi.github.io
   # Coding Pages
   - CO_REF: git.coding.net/bule/bule.coding.me.git
   - SecretId: ${SecretId}
   - SecretKey: ${SecretKey}