language: node_js
node_js:
- 8.9.0
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_955017c130ef_key -iv $encrypted_955017c130ef_iv -in .travis/id_rsa_pub.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name "lanpangzhi"
- git config --global user.email 875727617@qq.com
- npm install hexo-cli -g
install:
- npm install
script:
- hexo clean
- hexo generate
- hexo deploy
branches:
  only:
  - indigo
