name: hexo
on:
  push:
    branches:
      - indigo
env:
  GH_REF: github.com/lanpangzhi/lanpangzhi.github.io
  secretId: ${{ secrets.SECRETID }}
  secretKey: ${{ secrets.SECRETKEY }}

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout codes
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "10.14.0"

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "2.7"

      - name: Install and Deploy 
        run: |
          npm install hexo-cli -g
          npm install
          hexo generate
          hexo d
      - name: Deploy github
        run: |
          cd ./public
          git init
          git config user.name "lanpangzhi"
          git config user.email "875727617@qq.com"
          git add .
          git commit -m "GitHub Actions 自动部署"
          git push --force --quiet "https://${{secrets.CI_TOKEN}}@${{env.GH_REF}}" master:master
